[package]
name = "pagefind_web"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
bit-set = "0.5"
pagefind_stem = { path = "../pagefind_stem", features = ["english"] }
minicbor = { version = "0.15.0", features = ["derive"] }
wee_alloc = "0.4"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
