name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-musl
            cross: false
          - build: macos
            os: macos-latest
            rust: beta
            target: x86_64-apple-darwin
            cross: false
          - build: windows
            os: windows-latest
            rust: beta
            target: x86_64-pc-windows-msvc
            cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ matrix.rust }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust
        run: |
          rustup install ${{ matrix.rust }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install humane
        uses: XAMPPRocky/get-github-release@v1
        with:
          matches: ${{matrix.target}}
          owner: cloudcannon
          repo: humane
          token: "${{ secrets.GITHUB_TOKEN }}"
          install_path: ~/humane

      - name: Build WASM
        working-directory: ./pagefind_web
        run: ./local_build.sh

      - name: Build UI
        working-directory: ./pagefind_ui
        run: npm i && npm run build

      - name: Test Web
        working-directory: ./pagefind_web
        run: cargo test --release

      - name: Build Testing Binary
        working-directory: ./pagefind
        run: cargo build --release

      - name: Test Lib
        working-directory: ./pagefind
        run: cargo test --release --lib

      - name: Test CLI
        working-directory: ./pagefind
        run: TEST_BINARY=../target/release/pagefind ~/humane
